orbs:
  docker: circleci/docker@0.5.13
version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - docker/build:
          image: gokulakrishna/deriv-email-templates
      - docker/check
      - docker/push:
          image: gokulakrishna/deriv-email-templates
