orbs:
  docker: circleci/docker@0.5.13
  k8s: circleci/kubernetes@0.7.0
version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - docker/build:
          image: ${DOCKHUB_ORGANISATION}/deriv-email-templates
      - docker/check
      - docker/push:
          image: ${DOCKHUB_ORGANISATION}/deriv-email-templates
      - k8s/install-kubectl
      - run:
          command: |
            echo $CA_CRT | base64 --decode > ca.crt
            kubectl --server=${KUBE_SERVER} --certificate-authority=ca.crt --token=$SERVICEACCOUNT_TOKEN set image deployment/deriv-email-templates static-deriv-app-container=${DOCKHUB_ORGANISATION}/binary-static-offers:${CIRCLE_SHA1}
